### ISSUE TITLE
Support for 10.x

### ISSUE THREAD

**Issue by o2dazone** [derv82/Exchangent#1]
Not sure what has changed, but this tweak does not seem to work for me. iOS 10.2, iPhone 6s plus - I used the custom user-agent string `iPhone8C2/1405.304` (which is iOS 10.3.1), and when I register Exchange to my phone, the Exchange server still sees my original device user agent.

**Comment by derv82** [comment]
Oh, yea, this stopped working for me shortly after I released it.

I tried everything but can't find out how to spoof the device version.

I guess this project is deprecated now. Sorry. I'll update the README.

**Comment by narwhaldc** [comment]
Sadly, my happily jailbroken 9.x iPhone 6 got wrapped around the axle and I had no choice but to upgrade.  at the time, only viable non-11.x option was 10.3.3 (yeah, I have shsh blobs, but prometheus is a chore at best and I needed a JB version to get there and didn't have that anymore).

Anyway, so, now I have my non JB 10.3.3 iPhone alive and well, but sadly it will NOT talk to my exchange server.  I SUSPECT some residual of this tweak MIGHT be in play.  I DID restore my data onto the phone after DFU loading 10.3.3.

Any thoughts on if my suspicion is right?  If so, any thoughts on what file(s) might be borking things?  And, how to get them removed/modified to get things alive again w/o having to do a full rebuild of the phone and lose all my data?

**Comment by o2dazone** [comment]
Closing due to deprecation
